receivers:
  otlp:
    protocols:
      grpc:
      http: 
        endpoint: 0.0.0.0:4318
  webhookevent:
    endpoint: 0.0.0.0:1979
processors:
  batch:
  attributes:
    actions:
      - key: "alertname"
        action: insert
        value: "{{ .alertname }}"
      - key: "severity"
        action: insert
        value: "{{ .severity }}"
      - key: "status"
        action: insert
        value: "{{ .status }}"
exporters:
  logging:
    loglevel: debug
  kafka:
    brokers:
      - kafka:9092
    topic: otel-events
    protocol_version: 2.0.0
    encoding: "otlp_json"
    auth:
      tls:
        ca_file: /etc/otel/certs/ca.crt
        cert_file: /etc/otel/certs/client.crt
        key_file: /etc/otel/certs/client.key
        insecure: true
    retry_on_failure:
      enabled: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch,attributes]
      exporters: [kafka]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka]
    logs:
      receivers: [webhookevent]
      processors: [batch]
      exporters: [kafka]
