global:
  scrape_interval: 5s  # Reduce this to scrape more frequently (default is 1m)
  evaluation_interval: 5s  # Prometheus rule evaluation interval (optional)
scrape_configs:
  - job_name: 'nginx'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - nginx:80    # Target to probe with http.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.
alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

rule_files:
  - '/etc/prometheus/alert.rules.yml'
