- name: Process OpenTelemetry events
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        host: kafka.otel-demo.svc
        port: 9092
        topic: otel-events

  rules:
    - name: Trigger remediation
      condition: event.body != ""
      action:
        run_job_template:
          name: "[JT] Parse Kafka Payload"
          organization: eda_opentelemetry_workshop
          job_args:
            extra_vars:
              kafka_message: "{{ event }}"
