apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-demo
resources:
  - namespace.yaml
  - configmap-blackbox.yaml
  - configmap-prometheus.yaml
  - configmap-alertmanager.yaml
  - configmap-otel.yaml
  - deployments.yaml
  - services.yaml
  - route.yaml
  - alertmanagerconfig.yaml
  - rbac.yaml
  - nginx-build.yaml
