apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: demo-nginx
  namespace: otel-demo
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: demo-nginx
  namespace: otel-demo
spec:
  output:
    to:
      kind: ImageStreamTag
      name: demo-nginx:latest
  source:
    type: Binary
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
  triggers: []
