applications:
  - name: "Event-Driven Ansible"
    description: Event-Driven Ansible 
    organization: "eda_opentelemetry_workshop"
    state: present
    client_type: public
    auth_grant_type: password
