---
- name: CasC Deploy
  hosts: localhost
  gather_facts: false
  tasks:

    - name: Include vars
      ansible.builtin.include_vars:
        file: vars/custom.yaml

- name: Deploy OpenTelemetry stack on OpenShift
  ansible.builtin.import_playbook: playbooks/openshift_stack.yaml

- name: Configure Ansible Automation Platform 2.6
  ansible.builtin.import_playbook: playbooks/configure_aap.yaml
